name: tourcast
description: "A Flutter project for Cloudwalk interview process."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  http: ^1.2.1
  flutter_riverpod: ^2.5.1
  sqflite: ^2.3.3+1
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  sqflite_common_ffi: ^2.3.3

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  #assets:

analyzer:
  language:
    strict-raw-types: true
    strict-casts: true
